#!/bin/sh
if git commit -v --dry-run | grep '!testcode' >/dev/null 2>&1
then
  echo "Trying to commit test code."
  exit 1
else
  if git diff --cached locales/en.json | grep '\\n' >/dev/null 2>&1
  then
    echo "New line characters are forbiden in en.json, please split the lines in different translation terms."
    exit 1
  else
    exit 0
  fi
fi
