export default function generateFakeUser(
  guid = '123',
  name = 'Some User',
  username = 'someusermane',
) {
  return {
    getAvatarSource: jest.fn(), // mock UserModel method
    guid,
    name,
    username,
    type: 'user',
    subtype: false,
    time_created: '1468113204',
    time_updated: false,
    container_guid: '0',
    owner_guid: '0',
    site_guid: false,
    access_id: '2',
    language: 'en',
    icontime: '1523515420',
    impressions: 100,
    subscribers_count: 50,
    blocked: false,
    legacy_guid: false,
    featured_id: '725165605782560768',
    banned: 'no',
    website: '',
    briefdescription: '',
    dob: '',
    gender: 'private',
    city: '',
    merchant: {
      service: 'stripe',
      id: 'acct_Dsdfjdlsaf34243',
      exclusive: { enabled: true, amount: '10' },
    },
    boostProPlus: false,
    fb: false,
    mature: '1',
    monetized: '',
    signup_method: false,
    social_profiles: [],
    feature_flags: false,
    programs: ['affiliate'],
    plus: true,
    verified: true,
    founder: false,
    disabled_boost: false,
    boost_autorotate: true,
    categories: [
      'music',
      'nature',
      'news',
      'politics',
      'science',
      'technology',
      'education',
      'art',
      'health',
    ],
    wire_rewards: {
      description: '',
      rewards: { points: [], money: [] },
    },
    pinned_posts: [],
    mature_channel: '0',
    chat: true,
    subscribed: false,
    subscriber: true,
    boost_rating: '2',
    rewards: true,
    spam: '0',
    deleted: '0',
    eth_wallet: '0x6fffffdadae350ddd5a1777d5a1777a4f39f0317',
    rating: '1',
  };
}
