import {
  ACCENT_COLOR_DARK,
  ACCENT_COLOR_LIGHT,
  BACKGROUND_PRIMARY_COLOR_DARK,
  BACKGROUND_PRIMARY_COLOR_LIGHT,
  BACKGROUND_PRIMARY_HIGHLIGHT_COLOR_DARK,
  BACKGROUND_PRIMARY_HIGHLIGHT_COLOR_LIGHT,
  BACKGROUND_SECONDARY_COLOR_DARK,
  BACKGROUND_SECONDARY_COLOR_LIGHT,
  BACKGROUND_TERTIARY_COLOR_DARK,
  BACKGROUND_TERTIARY_COLOR_LIGHT,
} from '~/config/Config';

export type ColorsType = typeof LIGHT_THEME;
export type ColorsNameType = keyof typeof LIGHT_THEME;

export const LIGHT_THEME = {
  PrimaryBackground: BACKGROUND_PRIMARY_COLOR_LIGHT,
  PrimaryBackgroundHighlight: BACKGROUND_PRIMARY_HIGHLIGHT_COLOR_LIGHT,
  SecondaryBackground: BACKGROUND_SECONDARY_COLOR_LIGHT,
  TertiaryBackground: BACKGROUND_TERTIARY_COLOR_LIGHT,
  PrimaryText: '#43434D',
  SecondaryText: '#72727C',
  TertiaryText: '#9B9B9B',
  PrimaryButton: '#5DBAC0',
  PrimaryBorder: '#D3DBE3',
  Separator: '#323C3F',
  Done: '#4C92A4',
  Action: '#A5A5A5',
  Icon: '#7D7D82',
  IconActive: ACCENT_COLOR_LIGHT,
  IconDisabled: '#9B9B9B',
  IconBackground: '#E3E4E9',
  IconLight: '#F8FAFA',
  Link: ACCENT_COLOR_LIGHT,
  Alert: '#fd8b7c',
  InfoBackground: '#5A91BB',
  SuccessBackground: '#59A05E',
  DangerBackground: '#fd8b7c',
  WarningBackground: '#D49538',
  BaseBackground: '#D5D5d6',
  Green: '#00bca5',
  TabBorder: ACCENT_COLOR_LIGHT,
  AdminBadge: '#4caf50',
  VerifiedBadge: ACCENT_COLOR_LIGHT,
  Active: '#DADFE5',
  White: '#FFFFFF',
  Black: '#000000',
  Transparent: 'transparent',
  AvatarActive: '#ECDA51',
  AvatarCircled: '#7D7D82',
  MutedBackground: 'rgba(210, 219, 227, 0.4)',
  ButtonText: '#FFFFFF',
};

export const DARK_THEME: ColorsType = {
  PrimaryBackground: BACKGROUND_PRIMARY_COLOR_DARK,
  PrimaryBackgroundHighlight: BACKGROUND_PRIMARY_HIGHLIGHT_COLOR_DARK,
  SecondaryBackground: BACKGROUND_SECONDARY_COLOR_DARK,
  TertiaryBackground: BACKGROUND_TERTIARY_COLOR_DARK,
  PrimaryText: '#F2F2F2',
  SecondaryText: '#b9bbc0',
  TertiaryText: '#a1a5ab',
  PrimaryButton: '#5DBAC0',
  PrimaryBorder: '#53565A',
  Separator: '#323C3F',
  Done: '#4C92A4',
  Action: '#A5A5A5',
  Icon: '#AEB0B8',
  IconActive: ACCENT_COLOR_DARK,
  IconDisabled: '#797B82',
  IconLight: '#F8FAFA',
  IconBackground: '#404e53',
  Link: ACCENT_COLOR_DARK,
  Alert: '#fd8b7c',
  InfoBackground: '#5A91BB',
  SuccessBackground: '#59A05E',
  DangerBackground: '#fd8b7c',
  WarningBackground: '#D49538',
  BaseBackground: '#3f4b56',
  Green: '#00bca5',
  TabBorder: ACCENT_COLOR_DARK,
  AdminBadge: '#5cb860',
  VerifiedBadge: ACCENT_COLOR_DARK,
  Active: '#49525B',
  White: '#FFFFFF',
  Black: '#000000',
  Transparent: 'transparent',
  AvatarActive: '#ECDA51',
  AvatarCircled: '#AEB0B8',
  MutedBackground: 'rgba(65, 76, 87, 0.25)',
  ButtonText: '#000000',
};

export const SupermindGradient = ['#2B52E8', '#5238ED', '#9B0FA8'] as readonly [
  string,
  string,
  string,
];
