require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods',
         :deterministic_uuids => false


$RNFirebaseAsStaticFramework = true

platform :ios, '12.1'

target 'Minds' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  pod 'ffmpeg-kit-react-native', :subspecs => ['min-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  # use_frameworks! :linkage => :static

  pod 'RNPhotoEditor', :path => '../node_modules/react-native-photo-editor/ios'
  pod 'iOSPhotoEditor', :git => 'https://github.com/prscX/photo-editor', :branch => 'master'
  # pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  # pod 'RNSentry', :path => '../node_modules/@sentry/react-native'

  # pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

  # pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'MindsTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # Note for M1 Mac: enable flipper
  use_flipper!({ 'Flipper' => '0.122.0' })
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
        # Note for M1 Mac: uncomment next line
        # config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

target 'Minds-tvOS' do
  # Pods for Minds-tvOS

  target 'Minds-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Share' do
  # use_react_native!
  pod 'ffmpeg-kit-react-native', :subspecs => ['min-gpl'], :podspec => '../node_modules/ffmpeg-kit-react-native/ffmpeg-kit-react-native.podspec'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"], :hermes_enabled => true)

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
end
