# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Run all the tests"
  lane :test do
    scan(scheme: "Minds")
  end

  desc "Build release"
  lane :buildrelease do
    match(type: "appstore")
    increment_build_number(xcodeproj: "Minds.xcodeproj", build_number: latest_testflight_build_number + 1)
    build_app(scheme: "Minds")
  end

  desc "Push a new beta build to TestFlight"
  lane :testflight do
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
