# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Authenticate with App Store Connect"
  lane :auth do 
    app_store_connect_api_key(
      key_id: "SSN6GGXR42",
      issuer_id: "69a6de78-30ef-47e3-e053-5b8c7c11a4d1",
      key_content: "#{ENV["APP_STORE_CONNECT_API_KEY"]}",
      is_key_content_base64: true,
      duration: 1200, # optional
      in_house: false, # optional but may be required if using match/sigh
    )
  end

  desc "Run all the tests"
  lane :test do
    scan(scheme: "Minds")
  end

  desc "Build release"
  lane :buildrelease do
    sh("echo $SENTRY_IOS_PROPERTIES | base64 --decode > ../sentry.properties")
    api_key = auth
    match(
      api_key: api_key,
      type: "appstore",
      app_identifier:["com.minds.mobile","com.minds.mobile.Share"]
    )
    increment_build_number(xcodeproj: "Minds.xcodeproj", build_number: latest_testflight_build_number(api_key: api_key) + 1)
    build_app(scheme: "Minds")
  end

  desc "Push a new beta build to TestFlight"
  lane :testflight do
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: auth)
  end

  desc "Prepare sentry release"
  lane :preparesentry do
    version = get_version_number(
      xcodeproj: "Minds.xcodeproj",
      target: "Minds"
    )
    sh("echo " + version + " > ../version")

    sentry_upload_dsym(
      org_slug: 'minds-inc',
      project_slug: 'mobile',
      dsym_path: 'Minds.app.dSYM.zip'
    )

    sentry_create_release(
      org_slug: 'minds-inc',
      project_slug: 'mobile',
      version: version ,
      finalize: false
    )
  end

end
