function load() {
  let notifications = [
    {
      uuid: '4a427b80-c53d-11eb-a497-93e2755f275f',
      urn:
        'urn:notification:968187695744425997-4a427b80-c53d-11eb-a497-93e2755f275f',
      to_guid: '968187695744425997',
      from_guid: '100000000000000519',
      from: {
        guid: '100000000000000519',
        type: 'user',
        subtype: false,
        time_created: '1623077876',
        time_updated: false,
        container_guid: false,
        owner_guid: false,
        site_guid: false,
        access_id: false,
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'Minds',
        username: 'minds',
        icontime: '1623077876',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: false,
        briefdescription: '',
        gender: false,
        city: false,
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: false,
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: null,
        pinned_posts: [],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 0,
        last_avatar_upload: '0',
        canary: false,
        theme: false,
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        liquidity_spot_opt_out: 0,
        urn: 'urn:user:100000000000000519',
        subscribed: true,
        subscriber: false,
        boost_rating: 1,
        pro: false,
        pro_published: false,
        rewards: false,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
      entity_urn: 'urn:user:968187695744425997',
      entity: {
        guid: '968187695744425997',
        type: 'user',
        subtype: false,
        time_created: '1556209934',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: ['technology', 'crypto', 'blockchain', 'music', 'art'],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'Juan',
        username: 'juanmsolaro',
        language: 'en',
        icontime: '1613843786',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription: 'Full Stack Developer at @minds',
        gender: '',
        city: 'Colonia Avellaneda',
        merchant: {
          service: 'stripe',
          id: 'acct_1Gj1tZDf4yhop99j',
        },
        boostProPlus: false,
        fb: false,
        mature: 1,
        monetized: '',
        signup_method: false,
        social_profiles: [
          {
            key: 'linkedin',
            value: 'linkedin.com/in/juan-manuel-solaro-730a48184',
          },
        ],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: true,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: {
          description: '',
          rewards: {
            points: [],
            money: [
              {
                amount: '1',
                description: 'VIP',
              },
            ],
            tokens: [
              {
                amount: '1',
                description: 'Common Citizen',
              },
              {
                amount: '2',
                description: 'Adventurer',
              },
              {
                amount: '3',
                description: 'Hero',
              },
            ],
          },
        },
        pinned_posts: ['1234531362564866048'],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 5,
        last_avatar_upload: '1565703100',
        canary: true,
        theme: 'dark',
        toaster_notifications: true,
        mode: 0,
        btc_address: '1M27rFgyxqGdbmyjABu7J3pqa2YPhFs4mp',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJkbzZ2LWhfWGhxMDpBUEE5MWJGQ3N0T3c4QzdPR3M0ZjZDZ3VzWWhma0JScGstMF9rN0xValQyUmJhRGtmTmJpZXlSSG1oRmRJeTlRRTlEY0tsV0ZPZFNxR3hfNU9YQnI3VXFUV3paMDFNZ1ZSYm9fVXM3WjZrQVpiX2ZtdDU2akh2LVdUNXk3RzM4ZlBIQ1QwSDZEdXU5RyJ9',
        hide_share_buttons: true,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [
          'language-sidebar-2020',
          'discovery-disclaimer-2020',
        ],
        liquidity_spot_opt_out: 0,
        chat: true,
        urn: 'urn:user:968187695744425997',
        subscribed: false,
        subscriber: false,
        boost_rating: 1,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0xd3004e3cbA40079c31F80F0C465aacc34588bd79',
        rating: 1,
        disable_autoplay_videos: true,
        yt_channels: [],
      },
      read: true,
      created_timestamp: 1622815259,
      type: 'token_rewards_summary',
      data: {
        tokens_formatted: '0.332',
        usd_formatted: '0.36',
      },
      merged_from_guids: [],
      merged_from: [],
      merged_count: 0,
      merge_key:
        '52161ea64224a6ac08d653f9dd40b6e568d55362945138174507bf566e9e5e63',
    },
  ];

  return {
    notifications,
    'load-next': 'aaaaaa',
    status: 'sucess',
  };
}

/**
 * comment service data faker
 * @param {integer} count
 */
export function notificationsServiceFaker() {
  return { load: load };
}
