.build_base:
  stage: build
  needs: ['test:quality']
  interruptible: true

# Android common build steps
.prepare_build_android: &prepare_build_android
  image: msantang78/ci-mobile-android:latest
  tags: [minds-ci]
  before_script:
    - !reference [.getversion, script]
    - export ANDROID_SDK_HOME=$CI_PROJECT_DIR
    - export GRADLE_USER_HOME="$CI_PROJECT_DIR/.gradle"
    - sudo sysctl fs.inotify.max_user_watches=524288
    - sudo sysctl -p
    - sudo ln -s /lib/x86_64-linux-gnu/libncurses.so.6 /lib/x86_64-linux-gnu/libncurses.so.5
    - sudo ln -s /lib/x86_64-linux-gnu/libncursesw.so.6 /lib/x86_64-linux-gnu/libtinfo.so.5
    - yarn install --frozen-lockfile
    - cd android
    - bundle install --path=vendor/bundle
  artifacts:
    name: 'Minds APK'
    paths:
      - $APK_NAME
    expire_in: 45 days
    when: on_success

# Move the apk to the root folder
.move_apk: &move_apk
  - mv app/build/outputs/apk/release/app-release.apk ../$APK_NAME

# Builds iOS production ipa
build:ios:
  image: macos-12-xcode-14
  tags: [saas-macos-medium-m1]
  artifacts:
    name: 'Minds IPA'
    paths:
      - 'ios/Minds.ipa'
    expire_in: 45 days
    when: on_success
  before_script:
    - 'mkdir -p ~/.ssh' # we github to the known_hosts file (fix hanging when cloning secrets repo)
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer" | bash
    - mv .secure_files/id_rsa ~/.ssh/id_rsa
    - echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - chmod 700 ~/.ssh
    - chmod 644 ~/.ssh/known_hosts
    - ssh-add ~/.ssh/id_rsa
    - yarn install --frozen-lockfile --ignore-engines
    - cd ios
    - pod install
  extends: .build_base
  script:
    - fastlane buildrelease # | tee -a ios-job.log
  rules:
    - !reference [.rule_automatic_nonpatch_manual_others, rules]
    - !reference [.rule_release_branch, rules]
    - !reference [.rule_native_branch, rules]
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: manual

# Build Android production Full Version (Higher version code)
build:android:
  <<: *prepare_build_android
  extends: .build_base
  script:
    - bundle exec fastlane assemble_build
    - *move_apk
  rules:
    - !reference [.rule_version_tag, rules]
    - !reference [.rule_release_branch, rules]
    - !reference [.rule_never_nightly, rules]
    - !reference [.rule_never_mr_pipes, rules]
    - when: manual

# Production build for QA of MR
# Runs only on native branches
build:android:mr:
  <<: *prepare_build_android
  extends: .build_base
  variables:
    APK_FILENAME: 'Minds-$CI_COMMIT_REF_SLUG.apk'
  cache:
    key: '$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
      - android/vendor/bundle
      - .gradle/caches
      - .gradle/wrapper
      - .android/build-cache/
  script:
    - cp app/debug.keystore debug.keystore
    - export ENVFILE=".env.review"
    - bundle exec fastlane assemble_mr_build
    - *move_apk
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://minds-repo.s3.amazonaws.com/mobile/$APK_FILENAME
    on_stop: build:cleanup
  rules:
    - !reference [.rule_never_nightly, rules]
    - !reference [.rule_native_branch, rules]
    - !reference [.rule_custom_tag, rules]

# Play store version (Lowest version code)
build:android:store:
  <<: *prepare_build_android
  extends:
    - .build_base
    - .rule_version_tag
  script:
    - "sed -i 's/<uses-permission android:name=\"android.permission.REQUEST_INSTALL_PACKAGES\" \\/>//g' ./app/src/main/AndroidManifest.xml"
    - bundle exec fastlane assemble_build play:true
    - *move_apk
  rules:
    - !reference [.rule_version_tag, rules]
    - !reference [.rule_release_branch, rules]
    - !reference [.rule_never_nightly, rules]
    - !reference [.rule_never_mr_pipes, rules]
    - when: manual
  artifacts:
    name: 'Minds Store APK'
    paths:
      - $APK_NAME
    expire_in: 45 days
    when: on_success

# Cleanup APK from merged MRs
build:cleanup:
  extends:
    - .build_base
    - .except_nightly
    - .only_native
  image: msantang78/ci-mobile-android:latest
  tags: [minds-ci]
  when: manual
  variables:
    APK_FILENAME: 'Minds-$CI_COMMIT_REF_SLUG.apk'
    IPA_FILENAME: 'Minds-$CI_COMMIT_REF_SLUG.ipa'
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://minds-repo.s3.amazonaws.com/mobile/$APK_FILENAME
    action: stop
  cache:
    key: '$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  before_script:
    - yarn install --frozen-lockfile
  script:
    - export TARGET_NAME=$APK_FILENAME
    - !reference [.delete_browserstack, script]
    - export TARGET_NAME=$IPA_FILENAME
    - !reference [.delete_browserstack, script]
